[[statement]]
userselectALL = "SELECT * FROM user"
apikeysInfoRes = "SELECT * FROM apikeys"
apikeysRes = "SELECT key FROM apikeys"
userselectSpecifiedMcUsername = "SELECT mcname FROM user"


[[statement.parameters]]
userinput = "INSERT INTO user VALUES(?, ?, ?, ?, ?, ?)"
apiInput = "INSERT INTO apikeys VALUES(?, ?, ?)"
userselect = "SELECT * FROM user where userid = ?"
userselectinfo = "SELECT * FROM user where userid = ? and mcuuid = ?"


[statement.tables]
usertable = """
CREATE TABLE IF NOT EXISTS user (
	userid TEXT NOT NULL UNIQUE,
	uname TEXT NOT NULL ,
	mcname TEXT NOT NULL ,
	mcuuid TEXT NOT NULL ,
	interval INTEGER NOT NULL ,
	timestamp INTEGER NOT NULL 
	)
"""
# TODO: Potentially add usernames to restrict amount of fetches
api = """
CREATE TABLE IF NOT EXISTS apikeys (
	key TEXT PRIMARY KEY,
	belongs_to TEXT NOT NULL UNIQUE,
	donated_by TEXT
	)
"""
[statement.alter]
addcolumn = "ALTER TABLE {table name} ADD COLUMN {name} {type}"
# Add javascript function to replace ?1 and ?2 without values()
addincrementcolumn = "ALTER TABLE ?1 ADD COLUMN ?2 INTEGER AUTOINCREMENT "

[statement.update]
updateUserTableUserCol = "UPDATE user SET mcuuid = ? WHERE mcname = ?"

[statement.schema]
alltableres = """
SELECT 
    *
FROM 
    sqlite_schema
"""